### PR TITLE
Use Zygote process

### LINKED ISSUE #755: Issue with handling signals in containers
We currently use tokio for the communication with containerd in the shim.
Many of the shims built on top of runwasi also use tokio, for example the wasmtime shim.
With our current implementation `tokio::signal` is broken for wasm containers created by runwasi shims.

The reason for this is a bit involved.
With out current implementation, a container inherits the global state of the shim when the container is created.
Tokio's signal handling depends on some global state, and in particular uses the self pipe trick.
This means that the pipe used for handling signals will be shared by the shim and all the wasm containers spawned by it.
We currently don't do any special signal handling inside of the shim, so this doesn't affect us where there's one container per shim.
The problem appears when one shim is managing more than one container.

### PR DESCRIPTION
**Pull request by jprendes**
This PR introduces a zygote process (a very small process cloned early on during shim startup), from which new containers are created. This effectively decouples the global state of the shim from the state of the container process.

Fixes #755 and #357

### CODE REVIEW

**Comment by jprendes** [comment]
This build on the changes from #774 
For a diff without the changes in #774 see https://github.com/jprendes/runwasi/compare/remove-engine..zygote

The benchmark results show no change in performance w.r.t. the scheduled nightly runs:
* https://github.com/containerd/runwasi/actions/runs/12810771961/job/35718583098?pr=775
* https://github.com/containerd/runwasi/actions/runs/12810771961/job/35718583943?pr=775#step:9:86

File: crates/containerd-shim-wasm/src/sys/unix/container/instance.rs [hunk 1]
```diff
@@ -39,36 +40,52 @@ impl<E: Engine + Default> SandboxInstance for Instance<E> {
...
-        }
-        if let Ok(f) = open(cfg.get_stdout()) {
-            builder = builder.with_stdout(f);
-        }
-        if let Ok(f) = open(cfg.get_stderr()) {
-            builder = builder.with_stderr(f);
-        }
-
-        let container = builder.as_init(&bundle).with_systemd(false).build()?;
+        let (root, state) = Zygote::global()
```
Comment (Mossaka) [inline crates/containerd-shim-wasm/src/sys/unix/container/instance.rs:52]: Great, nice interface to use

Comment (Mossaka) [reply crates/containerd-shim-wasm/src/sys/unix/container/instance.rs:52]: I would like to see the memory usage of this zygote process vs. the cloned shim process running containers

**Review by andreiltd — APPROVED** [review]

File: crates/containerd-shim-wasm/src/sys/unix/container/instance.rs (hunk 1 above)
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sys/unix/container/instance.rs:52]: ### Memory usage as reported by `VmPeak` in `/proc/xxx/status`

Without zygote
```
Shim peak memory usage was: 3341772 kB
```

With zygote:
```
Shim peak memory usage was: 3342252 kB
Zygote peak memory usage was: 31056 kB
```

---

I am a bit surprised by the memory usage of the shim, I expected it to consume less memory.

**Review by jsturtevant — APPROVED** [review]
This is really great work!  Looking forward to seeing less sporadic CI failures :rocket:

Do I understand correctly that the container creation would look like:

```
->shim 
     ->zygote (cloned from shim)
          -> container 1 (message sent from shim to zygote; cloned from zygote)
          -> container 2 (message sent from shim to zygote; cloned from zygote)
```

**Comment by jprendes** [comment]
Yes, that's correct.

We could still see issues if we ever "pollute" the zygote. We do create an engine inside the zygote before cloning the process, and if that has global state, starts threads, etc, it can be a problem.

Currently the engine struct for all our shims are very simple, so that's not an issue. 

I'm thinking on addressing that as part of the split engine-precompiler.

File: crates/containerd-shim-wasm/src/sys/unix/container/instance.rs (hunk 1 above)
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sys/unix/container/instance.rs:52]: Revisiting the numbers, for wasmtime the shim peaks at ~19000 kB of resident memory with or without the zygote.
The zygote itself peaks at 5500kB of resident memory.

**Review by Mossaka — APPROVED** [review]
LGTM!
