### PR TITLE
cgroup: v2: do not set subtree_control for new cg

### LINKED ISSUE #35: Others("Device or resource busy (os error 16)"): unknown
After [building ](https://github.com/containerd/runwasi#build)and [running the demo example](https://github.com/containerd/runwasi#examples), I got the following error:

```
sudo ctr run --rm --runtime=io.containerd.wasmtime.v1 docker.io/library/wasmtest:latest testwasm
ctr: Others("Device or resource busy (os error 16)"): unknown
```

## investigation
The task is marked as CREATED:

```
sudo ctr task ls
TASK          PID    STATUS
testwasm13    0      CREATED
```

but get the following error when trying to delete it:

```
sudo ctr task rm testwasm13
ERRO[0000] unable to delete testwasm13                   error="task must be stopped before deletion: created: failed precondition"
ctr: task must be stopped before deletion: created: failed precondition
```

Also get a slightly different error when trying to "stop" it:

```
sudo ctr task kill -s SIGKILL testwasm13
ctr: cannot kill non-running container, current state: Exited(TaskState { s: PhantomData }): failed precondition
```

## other info
There seems to be two issues:

- the shim is and containerd are out of sync on the state of the shim. this leads to not being able to clean up the task/container
- There is an unhandled exception in https://github.com/containerd/runwasi/blob/e266bbbb51f2a2e1e207304f87090717278bab45/src/instance.rs#L190 This causes the `Device or resource busy (os error 16)`

## versions
containerd version: `containerd containerd.io 1.6.7 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb`
shim version: built from `main` (e266bbbb51f2a2e1e207304f87090717278bab45)
linux version:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

It does works on my WSL instance:

```
containerd containerd.io 1.6.6 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1    

 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

### PR DESCRIPTION
**Pull request by cpuguy83**
A cgroup can either have delegations (`cgroup.subtree_control` is populated) OR it can have processes in it, but not both. So we need to make sure that we don't add any controllers to the new cgroup's `cgroup.subtree_control` BUT we should continue to do so for any parents that we create.

Fixes #35

### CODE REVIEW

**Comment by cpuguy83** [comment]
Ok this is good to go.

File: crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs [hunk 1]
```diff
@@ -26,16 +27,35 @@ impl CgroupV2 {
...
 
             if full.exists() {
+                debug!("skipping creation of existing cgroup: {}", full.display());
                 // This is a pre-existing cgroup, so we won't touch subtree control.
                 continue;
             }
 
+            if full.to_str() == safe_join(self.base.clone(), self.path.clone())?.to_str() {
+                // This is the last element in the path, so we don't need to create it.
+                // The cgrouop will get created later when we try to write to a file in it.
```
Comment (jsturtevant) [inline crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs:45]:
```suggestion
                // The cgroup will get created later when we try to write to a file in it.
```

File: crates/containerd-shim-wasm/src/sandbox/exec.rs [hunk 2]
```diff
@@ -145,7 +145,7 @@ pub unsafe fn fork(cgroup: Option<&dyn Cgroup>) -> Result<Context, Error> {
             }
         }
     } else {
-        debug!("no CAP_SYS_ADMIN, not creating new namespaces");
+        debug!("no CAP_SYS_ADMIN, not creating setting cgroup");
```
Comment (jsturtevant) [inline crates/containerd-shim-wasm/src/sandbox/exec.rs:148]: "not creating cgroup"?

File: crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs [hunk 3]
```diff
@@ -26,16 +27,35 @@ impl CgroupV2 {
...
+        for d in p.iter() {
             full = safe_join(full.clone(), PathBuf::from(d))?;
 
             if full.exists() {
+                debug!("skipping creation of existing cgroup: {}", full.display());
                 // This is a pre-existing cgroup, so we won't touch subtree control.
                 continue;
             }
 
+            if full.to_str() == safe_join(self.base.clone(), self.path.clone())?.to_str() {
```
Comment (jsturtevant) [inline crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs:43]: Is this the only place that the full path (base + path) is calcuated? might consider making base+path a method on the implementation if reused somewhere

**Review by jsturtevant — COMMENTED** [review]
lgtm

File: crates/containerd-shim-wasm/src/sandbox/exec.rs (hunk 2 above)
Comment (cpuguy83) [reply crates/containerd-shim-wasm/src/sandbox/exec.rs:148]: In this case it would be not setting the cgroup because the cgroup is already created and just passed into this function.

Comment (jsturtevant) [reply crates/containerd-shim-wasm/src/sandbox/exec.rs:148]: then it would be?

```suggestion
        debug!("no CAP_SYS_ADMIN, not setting cgroup");
```

Comment (cpuguy83) [reply crates/containerd-shim-wasm/src/sandbox/exec.rs:148]: lol, I didn't even notice that `creating` was in there after you pointed it out.

**Comment by cpuguy83** [comment]
Fixed comments

**Review by devigned — APPROVED** [review]
lgtm!

**Review by jsturtevant — APPROVED** [review]
