### PR TITLE
Remove complexity from wait API

### LINKED ISSUE #326: Process crashes and hangs if invalid entrypoint provided
Using the lastest commit `commit df35a387799248b3e82b52609890d02f58a411e5`

Pass an invalid entrypoint and the process hangs for ~30 seconds eventually spitting out the error `Others("failed to receive. \"waiting for init ready\". BrokenChannel")`. During which time no logs are output to containerds log stream.

```
❯ sudo ./ctr run --rm --runtime=io.containerd.wasmtime.v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest testwasm /something.exe echo

~ 30sec

ctr: Others("failed to receive. \"waiting for init ready\". BrokenChannel"): unknown
```

Running it a second time and the process hangs indefinitely. 

```
❯ sudo ./ctr run --rm --runtime=io.containerd.wasmtime.v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest testwasm /something.exe echo
hangs....
```

## analysis
Was able to track that down to the failed process earlier where it didn't clean up properly ending up with 

```
bind(5, {sa_family=AF_UNIX, sun_path="/run/containerd/dfe5ace9c8dbc561.sock"}, 40) = -1 EADDRINUSE (Address already in use)
```

I've tracked this error down `"failed to receive. \"waiting for init ready\". BrokenChannel"` to https://github.com/containers/youki/blob/57ffefe89318df1cd1d1487c3cbcd4576a2d4dea/crates/libcontainer/src/process/channel.rs#L166-L173

I believe reason for the first "init ready" is somewhere in 

https://github.com/containerd/runwasi/blob/main/crates/containerd-shim-wasm/src/sys/unix/container/executor.rs#L87C1-L106

and it not handling the errors properly.  Not sure if this is libcontainer or runwasi handling it wrong.

### LINKED ISSUE #339: Simplify the code that waits for the container exit code
Currently to capture the exit code of a container during the wait call we have:
* a `Mutex` + `Condvar` pair in [`shim.rs`](https://github.com/containerd/runwasi/blob/main/crates/containerd-shim-wasm/src/sandbox/shim.rs#L43)
* a `mpsc` channel bridging between [`shim.rs`](https://github.com/containerd/runwasi/blob/main/crates/containerd-shim-wasm/src/sandbox/shim.rs#L1013) and [`instance.rs`](https://github.com/containerd/runwasi/blob/main/crates/containerd-shim-wasm/src/sandbox/instance.rs#L165)
* a `Mutex` + `Condvar` pair in [`instance.rs`](https://github.com/containerd/runwasi/blob/main/crates/containerd-shim-wasm/src/sandbox/instance.rs#L12)

This, specially managing the Condvar, is error prone. Specially when we consider the early returns from error handling. This is for instance the root cause of https://github.com/containerd/runwasi/issues/326.

All this complexity can probably be simplified, and/or abstracted in a way that makes it more resiliant to error situations.

### PR DESCRIPTION
**Pull request by jprendes**
This PR simplifies the API around the `Instance::wait` method and around `TaskState` and `InstanceData`.
Fixes #339.

Note that a side effect of this PR is that it fixes #326 but it shouldn't be considered a substitute for #340.

### CODE REVIEW

File: crates/containerd-shim-wasm/src/sandbox/sync.rs [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+
+struct WaitableCellImpl<T> {
+    // Ideally we would just use a OnceLock, but it doesn't
+    // have the `wait` and `wait_timeout` methods, so we use
+    // a Condvar + Mutex pair instead.
+    // We can't guard the OnceCell **inside** the Mutex as
+    // that would produce ownership problems with returning
+    // `&T`. This is because the mutex doesn't know that we
+    // won't mutate the OnceCell once it's set.
+    mutex: Mutex<()>,
```
Comment (Mossaka) [inline crates/containerd-shim-wasm/src/sandbox/sync.rs:19]: Initially, it seems strange to me that the `Mutex` type isn't really guarding anything. After I read the comment, I understand that we can't guard the `OnceCell` due to the use of `&T` within the OnceCell issue. 

I am wondering if we can change it to `cell: Mutex<Option<T>>` instead of `OnceCell<T>`?

File: crates/containerd-shim-wasm/src/sandbox/sync.rs [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+
+    /// If the `WaitableCell` is empty when this guard is dropped, it will set with the result of `f`.
+    pub fn set_guard_with<R: Into<T>>(&self, f: impl FnOnce() -> R) -> impl Drop {
+        let cell = (*self).clone();
+        WaitableCellSetGuard { f: Some(f), cell }
+    }
+
+    /// Wait for the WaitableCell to be set a value.
+    pub fn wait(&self) -> &T {
+        let value = self.wait_timeout(None);
```
Comment (Mossaka) [inline crates/containerd-shim-wasm/src/sandbox/sync.rs:88]: When `wait_timeout` returns a `None` value, this could be dangerous to do `unwrap_unchecked()`.

Could you please add a `assert` statement to check the value is not `None` at runtime at least?

File: crates/containerd-shim-wasm/src/sandbox/sync.rs [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+            Some(dur) => cvar
+                .wait_timeout_while(guard, dur, |_| self.inner.cell.get().is_none())
+                .map(|(guard, _)| guard)
+                .unwrap(),
+        };
+        self.inner.cell.get()
+    }
+}
+
+impl<T, R: Into<T>, F: FnOnce() -> R> Drop for WaitableCellSetGuard<T, R, F> {
```
Comment (Mossaka) [inline crates/containerd-shim-wasm/src/sandbox/sync.rs:113]: Could you please add some comments explaining this usage?

File: crates/containerd-shim-wasm/src/sandbox/sync.rs [hunk 4]
```diff
@@ -0,0 +1,117 @@
+use std::cell::OnceCell;
+use std::sync::{Arc, Condvar, Mutex};
+use std::time::Duration;
+
+/// A cell where we can wait (with timeout) for
+/// a value to be set
+pub struct WaitableCell<T> {
```
Comment (Mossaka) [inline crates/containerd-shim-wasm/src/sandbox/sync.rs:7]: I'd love to see some tests to ensure `WaitableCell<T>` behaves as expected in concurrent senarios.

File: crates/containerd-shim-wasm/src/sandbox/instance.rs [hunk 5]
```diff
@@ -107,7 +104,9 @@ impl<Engine: Send + Sync + Clone> InstanceConfig<Engine> {
 
 /// Represents a WASI module(s).
 /// Instance is a trait that gets implemented by consumers of this library.
-pub trait Instance {
+/// This trait requires that any type implementing it is `'static`, similar to `std::any::Any`.
+/// This means that the type cannot contain a non-`'static` reference.
+pub trait Instance: 'static {
```
[the remark this answers is not in the document]
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sandbox/instance.rs:109]: This is so that we can move an `Arc<Instance>` into a thread.
We call `instance.wait()` in a thread since it's now a blocking call.

The `'static` here doesn't mean that any `Instance` variable has to be a global static variable. It does mean that you *could* if you wanted, create a global static of that type.
For example, a `String` would satisfy `'static`, as would `'static str`. However `'a str` would not.
Anything we think of as an _owned_ type, would satisfy `'static`, and `'static` references too. But non `'static` references would not.

The alternative to this is having a _shared state_ object that the `Instance` can return to signal the end of the process (similar-ish to what we had before). What I mean by _shared state_ is for example, and `mpsc::channel` or even a clone of the `WaitableCell`. Before this change the `Mutex` + `CondVar` tuple was the shared state.

I personally prefer imposing `'static` (which I think is a low price to pay) and having a simpler API, but I'd love to hear your thoughts.

File: crates/containerd-shim-wasm/src/sandbox/sync.rs (hunk 1 above)
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sandbox/sync.rs:19]: The problem with that is that we wouldn't be able to return a reference to it's content. The general use case for a mutex doesn't know that once set the content can't change, and thus it's safe to share a reference to it with the world.
We can work around this issue if we require `Clone` and we return a `clone` of the type. That would work for the `(u32, DateTime)` exit result. It would make the `WaitableCell` less generic, but that might be fine, it's not like we are using it for anything else.

I am also considering whether I should just remove the `WaitableCell` and replace it with a `sync::OnceCell` from the `once-cell` crate (which is the inspiration for the `OnceCell` and `OnceLock` of the rust std lib).
Unfortunately when the std lib adopted them, they didn't include the `wait` method.
The main problem with this is that while they have a `wait` method, they don't have a `wait_timeout` method. The only place where we use timeouts in the wait is on tests, and it might be fine to just spin a thread in those cases.

File: crates/containerd-shim-wasm/src/sandbox/sync.rs (hunk 4 above)
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sandbox/sync.rs:7]: Will do!

File: crates/containerd-shim-wasm/src/sandbox/sync.rs (hunk 1 above)
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sandbox/sync.rs:19]: > I am wondering if we can change it to cell: Mutex<Option<T>> instead of OnceCell<T>?

In short, IIUC, no, that wouldn't solve the issue unless we require `Clone`.
But I'm happy to discuss further as I might be missing something.

File: crates/containerd-shim-wasm/src/sandbox/shim.rs [hunk 6]
```diff
@@ -35,286 +36,175 @@ use shim::api::{StatsRequest, StatsResponse};
...
+            Self::Instance(i) => i.wait_timeout(t),
+            Self::Nop(i) => i.wait_timeout(t),
         }
-        self.base.as_ref().unwrap().wait(waiter)
     }
 }
 
-type EventSender = Sender<(String, Box<dyn MessageDyn>)>;
+struct InstanceData<T: Instance> {
+    instance: InstanceOption<T>,
```
[the remark this answers is not in the document]
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sandbox/shim.rs:86]: In some cases this is a `Nop` instance, in others this is a `T` instance.
See:
* https://github.com/containerd/runwasi/blob/32b4fba42c19b5550be2184e45626eaa16ab4760/crates/containerd-shim-wasm/src/sandbox/shim.rs#L629
* https://github.com/containerd/runwasi/blob/32b4fba42c19b5550be2184e45626eaa16ab4760/crates/containerd-shim-wasm/src/sandbox/shim.rs#L704

IIUC, this is used for the _CRI pause_ container, whatever that means.

File: crates/containerd-shim-wasm/src/sandbox/sync.rs [hunk 7]
```diff
@@ -0,0 +1,117 @@
...
+}
+
+impl<T> WaitableCell<T> {
+    /// Creates an empty WaitableCell.
+    pub fn new() -> Self {
+        Self::default()
+    }
+
+    /// Creates a WaitableCell with a value.
+    pub fn with_value(val: T) -> Self {
```
[the remark this answers is not in the document]
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sandbox/sync.rs:59]: Good catch!
Leftover from a previous life of this code, will remove it.

File: crates/containerd-shim-wasm/src/sandbox/sync.rs (hunk 3 above)
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sandbox/sync.rs:113]: This type is internal to the module. It is an implementation details on how `set_guard_with` works.
I've added a few comments on this type, and more detaisl comments in `set_guard_with`.

File: crates/containerd-shim-wasm/src/sandbox/sync.rs (hunk 4 above)
Comment (jprendes) [reply crates/containerd-shim-wasm/src/sandbox/sync.rs:7]: Added unit tests

**Review by Mossaka — APPROVED** [review]
lgtm!
